<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class DuffelFlightService implements FlightServiceInterface
{
    protected string $baseUrl;
    protected string $accessToken;

    public function __construct()
    {
        $this->baseUrl = config('duffel.url');
        $this->accessToken = config('duffel.access_token');
    }

    /**
     * Get pre-configured HTTP client for Duffel
     */
    protected function client()
    {
        return Http::withToken($this->accessToken)
            ->withoutVerifying() // Bypasses local cURL error 60 (SSL cert missing in local PHP)
            ->withHeaders([
                'Duffel-Version' => 'v2',
                'Accept' => 'application/json',
            ]);
    }

    /**
     * Search Flights via Duffel
     */
    public function search(string $origin, string $destination, string $date, int $passengers): array
    {
        if (empty($this->accessToken)) {
            return [];
        }

        $passengerArray = [];
        for ($i = 0; $i < $passengers; $i++) {
            $passengerArray[] = ['type' => 'adult'];
        }

        $payload = [
            'data' => [
                'slices' => [
                    [
                        'origin' => strtoupper($origin),
                        'destination' => strtoupper($destination),
                        'departure_date' => $date,
                    ]
                ],
                'passengers' => $passengerArray,
                'return_offers' => true,
            ]
        ];

        $response = $this->client()->post($this->baseUrl . '/air/offer_requests', $payload);

        if ($response->failed()) {
            \Log::error("Duffel API Search Error: " . $response->body());
            return [];
        }

        $offers = $response->json('data.offers');
        if (!$offers) return [];

        $mappedFlights = [];
        // Extract the passenger IDs generated by Duffel for this offer request
        // We will need these when booking!
        $passengerIds = collect($response->json('data.passengers'))->pluck('id')->toArray();

        foreach ($offers as $offer) {
            $flightId = $offer['id'];

            // Save the offer so we can access price and passenger mappings
            Cache::put('duffel_offer_' . $flightId, [
                'offer' => $offer,
                'passenger_ids' => $passengerIds
            ], now()->addHours(2));

            $slice = $offer['slices'][0];
            $segment = $slice['segments'][0];
            
            $airline = $offer['owner']['name'] ?? 'Unknown';

            // Convert PT2H15M into 2h 15m
            $durationStr = str_replace(['PT', 'H', 'M'], ['', 'h ', 'm'], $slice['duration']);

            $mappedFlights[] = [
                'id' => $flightId,
                'airline' => $airline,
                'flight_number' => $segment['operating_carrier']['iata_code'] . $segment['operating_carrier_flight_number'],
                'origin' => $segment['origin']['iata_code'],
                'destination' => end($slice['segments'])['destination']['iata_code'],
                'departure_time' => $segment['departing_at'],
                'arrival_time' => end($slice['segments'])['arriving_at'],
                'duration' => $durationStr,
                'stops' => count($slice['segments']) - 1,
                'price' => $offer['total_amount'],
                'currency' => $offer['total_currency'],
            ];
        }

        return collect($mappedFlights)->sortBy('price')->values()->toArray();
    }

    /**
     * Price a specific flight
     */
    public function price(string $flightId): array
    {
        $cached = Cache::get('duffel_offer_' . $flightId);
        
        if (!$cached) {
            return [
                'total_price' => 0,
                'currency' => 'USD',
                'status' => 'expired'
            ];
        }

        return [
            'total_price' => $cached['offer']['total_amount'],
            'currency' => $cached['offer']['total_currency'],
            'status' => 'available'
        ];
    }

    /**
     * Book the Flight via Duffel
     */
    public function book(string $flightId, array $passengerDetails): array
    {
        $cached = Cache::get('duffel_offer_' . $flightId);
        
        if (!$cached) {
            throw new \Exception("Flight offer has expired.");
        }

        $offer = $cached['offer'];
        $duffelPassengerIds = $cached['passenger_ids'];

        $travelers = [];
        foreach ($passengerDetails as $index => $p) {
            $travelers[] = [
                'id' => $duffelPassengerIds[$index], // Match Duffel's generated passenger ID
                'phone_number' => '+447781432431', // Sandbox requires valid phone
                'email' => 'test@ramim.dev',
                'title' => 'mr',
                'gender' => 'm',
                'family_name' => $p['last_name'],
                'given_name' => $p['first_name'],
                'born_on' => '1990-01-01', // Sandbox dummy
            ];
        }

        $payload = [
            'data' => [
                'type' => 'instant',
                'selected_offers' => [$offer['id']],
                'passengers' => $travelers,
                'payments' => [
                    [
                        'type' => 'balance', // Balance payment type handles sandbox purchases
                        'currency' => $offer['total_currency'],
                        'amount' => $offer['total_amount']
                    ]
                ]
            ]
        ];

        $response = $this->client()->post($this->baseUrl . '/air/orders', $payload);

        if ($response->failed()) {
            return [
                'api_reference_id' => 'PNR' . strtoupper(Str::random(6)),
                'status' => 'mock_confirmed',
                'error' => "Duffel API Failed: " . $response->body()
            ];
        }

        $data = $response->json('data');

        return [
            'api_reference_id' => $data['booking_reference'] ?? $data['id'],
            'status' => 'confirmed'
        ];
    }
}
